# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://ua.sinoptik.ua/")
    self.driver.set_window_size(1085, 692)
    element = self.driver.find_element(By.LINK_TEXT, "10 днів")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "search_city").click()
    self.driver.find_element(By.ID, "search_city").send_keys("в")
    self.driver.find_element(By.CSS_SELECTOR, ".ac_over > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "#bd7 > .date").click()
    self.driver.close()
  
