# Generated by Selenium IDE
import pytest

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self, key_input):
    self.driver.get("https://ua.sinoptik.ua/%D0%BF%D0%BE%D0%B3%D0%BE%D0%B4%D0%B0-%D0%BA%D0%B8%D1%97%D0%B2")
    self.driver.set_window_size(891, 889)
    self.driver.find_element(By.CSS_SELECTOR, "#bd2 > .date").click()
    self.driver.find_element(By.CSS_SELECTOR, "#bd2c h2").click()
    self.driver.find_element(By.CSS_SELECTOR, "#bd4 > .date").click()
    element = self.driver.find_element(By.LINK_TEXT, "Понеділок")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "search_city").click()
    self.driver.find_element(By.ID, "search_city").send_keys(key_input)
    self.driver.find_element(By.ID, "search_city").send_keys(Keys.DOWN)
    self.driver.find_element(By.ID, "search_city").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "#bd4 > .weatherIco").click()
    self.driver.close()
  
